<a href="https://colab.research.google.com/github/comandi1969/AIFFEL_Online_Quest/blob/main/ML_With_Python/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EA%B8%B0%EC%B4%88_%EB%85%B8%EB%93%9C3_%ED%8C%90%EB%8B%A4%EC%8A%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    'Unnamed: 0': [0,1,2,3,4,5,6,'new',10],
    '메뉴': ['황금후라이드','승일양념치킨','간장치킨','마늘치킨','파닭','닭강정','양념반후라이드반','[인기]아이펠치킨','[베스트]풀잎치킨'],
    '가격': [12000,13000,14000,14000,14000,15000,13000,16000,9900],
    '호수' : ['10호','10호','9호','9호','11호','12호','10호','11호','10호'],
    '칼로리' : [1000.0,1400.0,1600.0,1800.0,1300.0,1500.0,1300.0,1200.0,np.nan],
    '할인율' : [0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.5,np.nan],
    '할인가' : [9600.0,10400.0,11200.0,11200.0,11200.0,12000.0,10400.0,8000.0,np.nan],
    '원산지' : ['국내산',np.nan,np.nan,np.nan,'브라질','브라질',np.nan,'국내산',np.nan]
})
df.to_csv('new_modudak.csv', index=False)
display(df)

  Unnamed: 0         메뉴     가격   호수     칼로리  할인율      할인가  원산지
0          0     황금후라이드  12000  10호  1000.0  0.2   9600.0  국내산
1          1     승일양념치킨  13000  10호  1400.0  0.2  10400.0  NaN
2          2       간장치킨  14000   9호  1600.0  0.2  11200.0  NaN
3          3       마늘치킨  14000   9호  1800.0  0.2  11200.0  NaN
4          4         파닭  14000  11호  1300.0  0.2  11200.0  브라질
5          5        닭강정  15000  12호  1500.0  0.2  12000.0  브라질
6          6   양념반후라이드반  13000  10호  1300.0  0.2  10400.0  NaN
7        new  [인기]아이펠치킨  16000  11호  1200.0  0.5   8000.0  국내산
8         10  [베스트]풀잎치킨   9900  10호     NaN  NaN      NaN  NaN

In [10]:
# Q. 다음 df 변수의 데이터에서 'Unnamed: 0' 컬럼을 삭제하고,
# 가격이 15000이상인 메뉴를 삭제해주세요.
df.drop('Unnamed: 0', axis=1, inplace=True)
df

          메뉴     가격   호수     칼로리  할인율      할인가  원산지
0     황금후라이드  12000  10호  1000.0  0.2   9600.0  국내산
1     승일양념치킨  13000  10호  1400.0  0.2  10400.0  NaN
2       간장치킨  14000   9호  1600.0  0.2  11200.0  NaN
3       마늘치킨  14000   9호  1800.0  0.2  11200.0  NaN
4         파닭  14000  11호  1300.0  0.2  11200.0  브라질
5        닭강정  15000  12호  1500.0  0.2  12000.0  브라질
6   양념반후라이드반  13000  10호  1300.0  0.2  10400.0  NaN
7  [인기]아이펠치킨  16000  11호  1200.0  0.5   8000.0  국내산
8  [베스트]풀잎치킨   9900  10호     NaN  NaN      NaN  NaN

In [11]:
cond = df['가격'] >= 15000
df
df[cond]
df.drop(df[cond].index, axis=0, inplace=True)
df

          메뉴     가격   호수     칼로리  할인율      할인가  원산지
0     황금후라이드  12000  10호  1000.0  0.2   9600.0  국내산
1     승일양념치킨  13000  10호  1400.0  0.2  10400.0  NaN
2       간장치킨  14000   9호  1600.0  0.2  11200.0  NaN
3       마늘치킨  14000   9호  1800.0  0.2  11200.0  NaN
4         파닭  14000  11호  1300.0  0.2  11200.0  브라질
6   양념반후라이드반  13000  10호  1300.0  0.2  10400.0  NaN
8  [베스트]풀잎치킨   9900  10호     NaN  NaN      NaN  NaN

In [15]:
# Q. 다음 df 변수의 데이터에서 결측치가 칼럼별로 몇 개가 있는지 확인하고,
# 결측치를 '빵꾸'로 채워주세요.
df = pd.read_csv('new_modudak.csv')
df.drop('Unnamed: 0', axis=1, inplace=True)
df.isnull().sum()
df = df.fillna('빵구')
df

          메뉴     가격   호수     칼로리  할인율      할인가  원산지
0     황금후라이드  12000  10호  1000.0  0.2   9600.0  국내산
1     승일양념치킨  13000  10호  1400.0  0.2  10400.0   빵구
2       간장치킨  14000   9호  1600.0  0.2  11200.0   빵구
3       마늘치킨  14000   9호  1800.0  0.2  11200.0   빵구
4         파닭  14000  11호  1300.0  0.2  11200.0  브라질
5        닭강정  15000  12호  1500.0  0.2  12000.0  브라질
6   양념반후라이드반  13000  10호  1300.0  0.2  10400.0   빵구
7  [인기]아이펠치킨  16000  11호  1200.0  0.5   8000.0  국내산
8  [베스트]풀잎치킨   9900  10호      빵구   빵구       빵구   빵구

In [23]:
# Q. 다음 df 변수의 데이터를 높은 칼로리 순으로 정렬해주세요.
df = pd.read_csv('new_modudak.csv')
df.drop('Unnamed: 0', axis=1, inplace=True)
df
#df.sort_values(by='칼로리', ascending=True)
#df.sort_values('칼로리', ascending=True)
df.sort_values(by=['칼로리', '가격'], ascending=[True, False])

          메뉴     가격   호수     칼로리  할인율      할인가  원산지
0     황금후라이드  12000  10호  1000.0  0.2   9600.0  국내산
7  [인기]아이펠치킨  16000  11호  1200.0  0.5   8000.0  국내산
4         파닭  14000  11호  1300.0  0.2  11200.0  브라질
6   양념반후라이드반  13000  10호  1300.0  0.2  10400.0  NaN
1     승일양념치킨  13000  10호  1400.0  0.2  10400.0  NaN
5        닭강정  15000  12호  1500.0  0.2  12000.0  브라질
2       간장치킨  14000   9호  1600.0  0.2  11200.0  NaN
3       마늘치킨  14000   9호  1800.0  0.2  11200.0  NaN
8  [베스트]풀잎치킨   9900  10호     NaN  NaN      NaN  NaN

In [50]:
df = pd.read_csv('new_modudak.csv')
df.drop('Unnamed: 0', axis=1, inplace=True)
df
df.info()
df['호수'] = df['호수'].str.replace('호', '')
df
df['호수'] = df['호수'].astype(int)
df
df['호수'].mean()
df['호수'].max()
df['호수'].min()
df['호수'].sum()
df['호수'].std()

0.97182531580755

In [83]:
# Q. 다음 df 변수의 데이터에서 '가격'의 3분위 수(75%)를 구하고,
# '호수'의 종류 수를 구하세요.
# 힌트 : describe(), nunique()를 사용해보세요.
df = pd.read_csv('new_modudak.csv')
df.drop('Unnamed: 0', axis=1, inplace=True)

df.nunique()
df['호수'].unique()
df['호수'].value_counts()

df.shape
third_quartile = df.describe().iloc[6, 0]
display(third_quartile)
df
#display(df.nunique())
#df['호수'].value_counts()

display(df.count())
len(df)
df.shape[0]

9

In [94]:
# Q. 다음 df 변수의 데이터에서 '가격' 칼럼의 상위 50% 값들만 뽑아서 df를 만들어주세요.
df = pd.read_csv('new_modudak.csv')
df.drop('Unnamed: 0', axis=1, inplace=True)
df.sort_values(by='가격', ascending=False)
df['가격'].quantile(.5)
cond = df['가격'].quantile(.5) < df['가격']
df[cond]

          메뉴     가격   호수     칼로리  할인율      할인가  원산지
5        닭강정  15000  12호  1500.0  0.2  12000.0  브라질
7  [인기]아이펠치킨  16000  11호  1200.0  0.5   8000.0  국내산