<a href="https://colab.research.google.com/github/comandi1969/AIFFEL_Online_Quest/blob/main/ML_With_Python/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EA%B8%B0%EC%B4%88_%EB%85%B8%EB%93%9C3_%ED%8C%90%EB%8B%A4%EC%8A%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    'Unnamed: 0': [0,1,2,3,4,5,6,'new',10],
    '메뉴': ['황금후라이드','승일양념치킨','간장치킨','마늘치킨','파닭','닭강정','양념반후라이드반','[인기]아이펠치킨','[베스트]풀잎치킨'],
    '가격': [12000,13000,14000,14000,14000,15000,13000,16000,9900],
    '호수' : ['10호','10호','9호','9호','11호','12호','10호','11호','10호'],
    '칼로리' : [1000.0,1400.0,1600.0,1800.0,1300.0,1500.0,1300.0,1200.0,np.nan],
    '할인율' : [0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.5,np.nan],
    '할인가' : [9600.0,10400.0,11200.0,11200.0,11200.0,12000.0,10400.0,8000.0,np.nan],
    '원산지' : ['국내산',np.nan,np.nan,np.nan,'브라질','브라질',np.nan,'국내산',np.nan]
})
df.to_csv('new_modudak.csv', index=False)
df

  Unnamed: 0         메뉴     가격   호수     칼로리  할인율      할인가  원산지
0          0     황금후라이드  12000  10호  1000.0  0.2   9600.0  국내산
1          1     승일양념치킨  13000  10호  1400.0  0.2  10400.0  NaN
2          2       간장치킨  14000   9호  1600.0  0.2  11200.0  NaN
3          3       마늘치킨  14000   9호  1800.0  0.2  11200.0  NaN
4          4         파닭  14000  11호  1300.0  0.2  11200.0  브라질
5          5        닭강정  15000  12호  1500.0  0.2  12000.0  브라질
6          6   양념반후라이드반  13000  10호  1300.0  0.2  10400.0  NaN
7        new  [인기]아이펠치킨  16000  11호  1200.0  0.5   8000.0  국내산
8         10  [베스트]풀잎치킨   9900  10호     NaN  NaN      NaN  NaN